name: MailBox
version: 1.1
main: me.markiscool.mailbox.MailboxPlugin
api-version: 1.13
author: MarkIsCool
description: Easily send mail to other players, even when they're offline.
commands:
  mail:
    usage: /<command>
    description: Base command - opens GUI
    aliases: [mailbox]
  mailfinished:
    usage: /<command>
    description: When you are done doing a task, run this command. A button is provided for this command.